# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7fad5c8c8ba8408be023507ca072c5f99a94382580364f0223d4a82c3eb527b3829ca42e5749eebc390d86f7802ea695e36c83344b352afeb50c9ec9c1ae61f

test:
  secret_key_base: 618edf23c58493ba1297834c02b386564c73782078249f3d92e3e83bc11ca7d0f2f0d6f69a6650642790ae580c48ec5e092fb7d435ff3d74134455e2e9ddac9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
